<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Veículos</title>
</head>
<body>
    <h1>Lista de veículos</h1>
    <li><a href="http://localhost:8080/veiculo/cadastro/<?= $modelo; ?>">

    <?php 
        foreach ($modelos as $modelo) {
            
            echo $modelo['Descricao'] . '</br>'; //. $modelo['Cor'] . '</br>';
            
        }
    ?>
    </a></li>
</body>
</html>